name: Code Secret Check using Trufflehog
on: push
jobs:
  trufflehog_security:
    runs-on: ubuntu-latest
    steps:
      - name: Old/new
        run: echo "New"
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build docker images
        run: docker pull trufflesecurity/trufflehog:latest
      - name: Check for secrets
        run: docker run -v "$PWD:/pwd" trufflesecurity/trufflehog:latest filesystem --directory=/pwd -j > trufflehog_report.json
      - name: Upload reports
        run: pip install requests; wget https://raw.githubusercontent.com/Narendran36/webapp/master/upload-results.py -O upload-results.py; chmod +x upload-results.py; python3 upload-results.py --host 127.0.0.1:8080 --api_key 3612f193be594f6ae0e1791555189be9e2d35258 --engagement_name "security-engagement" --result_file trufflehog --product_name "S3CUR1TY REPORT" --scanner "Trufflehog Scan"
      - name: Hello
        run: echo "Success!"
