name: Code Secret Check using Trufflehog
on: push
jobs:
  trufflehog_security:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build docker images
        run: docker pull trufflesecurity/trufflehog:latest
      - name: Check for secrets
        run: docker run -v "$PWD:/pwd" trufflesecurity/trufflehog:latest filesystem --directory=/pwd -j > trufflehog_report.json
